name: Automatic package publishing

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  
  build-and-publish:
    name: "Build packages and publish new versions"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - MoonCore
          - MoonCore.Blazor.FlyonUi
          - MoonCore.Extended
          - MoonCore.Unix
          - MoonCore.PluginFramework
          - MoonCore.PluginFramework.Generator
    
    steps:
      # Step 1: Clean environment
      - name: Clean up Environment
        run: |
          rm -rf ./*
          rm -rf ./.??*

      # Step 2: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Step 3: Download node_modules (only for MoonCore.Blazor.FlyonUi)
      - name: "Download node_modules"
        if: matrix.project == 'MoonCore.Blazor.FlyonUi'
        run: npm i
        working-directory: "Tests/MoonCore.Blazor.FlyonUi.Test.Frontend/Styles"
      
      # Step 4: Run tailwind extract script (only for MoonCore.Blazor.FlyonUi)
      - name: "Extracting used classes from tailwind build"
        if: matrix.project == 'MoonCore.Blazor.FlyonUi'
        run: npm run mappings
        working-directory: "Tests/MoonCore.Blazor.FlyonUi.Test.Frontend/Styles"
      
      # Step 5: Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0
      
      # Step 6: Run the publishing action
      - name: Publish on version change
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: Library/${{ matrix.project }}/${{ matrix.project }}.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}